### ISSUE TITLE
No macOS binary in downloads

### ISSUE THREAD

**Issue by retrography** [noembryo/KoHighlights#10]
I noticed there is no macOS binary included on the downloads page, so I created one using Platypus (https://sveinbjorn.org/platypus). Feel free to [download](https://www.dropbox.com/s/ka39wto85xrzbjw/KoHighlights.app.zip?dl=1) and include it. Obviously, you are welcome to test it or have it tested first. The package is supposed to be self-contained with no need for Python or library installations (the whole Python3 venv is included). I have also included the [few resource files](https://github.com/noembryo/KoHighlights/files/5636595/res.zip)
 that I have used to compile the package for future reference and reproduction purposes.

A screenshot:

<img width="1108" alt="Screenshot 2020-12-03 at 15 19 35" src="https://user-images.githubusercontent.com/5309061/101035626-1553e000-357b-11eb-9822-ed69fe86e18a.png">

**Comment by noembryo** [comment]
Oh, that was very kind of you.. Thank you!

Tried to run it with an older OSX 10.8.5 virtual machine I had, but failed.
What is the minimum MacOS version that I should use?

**Comment by retrography** [comment]
This is what I read on Platypus' website:

> The latest version is Platypus 5.3, released on November 25th, 2018. Platypus and Platypus-generated applications require macOS 10.8 or later, and are 64-bit Intel binaries. 

So, it is strange that it didn't work for you. Do you get any decipherable error? 

And does Platypus run on your VM? Maybe you can use the same Platypus profile I have shared with you to recreate the executable bundle.

**Comment by retrography** [comment]
On a second thought: Is it possible that the Python binary I have included is not compatible with 10.8? You can check that by entering the bundle's directory and looking into the resources to find the venv, then running the Python binary. Sorry if I am explaining the obvious, but I am not sure how much you know about MacOS.

**Comment by noembryo** [comment]
Well, *do* explain the obvious, because I know close to *nothing* about macs...

I found some shortcuts for `python`, `python3` and `python3.9`  inside the `bin` of the app, but none of then run...
From the terminal I could call only Python 2.7xx (the only one installed), so that is why the compiled app doesn't run.
It must be relying to the systems installed Python versions...

![mac1](https://user-images.githubusercontent.com/24675403/101089390-c4191000-35bd-11eb-887e-27838b83adf5.jpg)

**Comment by retrography** [comment]
Actually, the alias refers to the python binary within the directory. The `run.sh` file that I use to launch your `main.py` script uses the venv python anyway.

But here is the culprit:

> for OS X 10.9 and later

As reported [here](https://www.python.org/downloads/release/python-390/). The current python binaries are not compatible with macOS versions older than 10.9. We will have to find someone with a newer version of macOS to test the bundle. I will see if I can send it to a friend.

Sincerely, Platypus is not the best way to make self-contained Python-based executables, but I used it because I have a lot of issues running pyinstaller and py2app (which are the better solutions) since upgrading to macOS Big Sur.

**Comment by noembryo** [comment]
>Actually, the alias refers to the python binary within the directory.
Well, I can't find a Python binary *anywhere* inside the bin directory.
What you're seeing in the screenshot is the Info of the `python` alias, that refers to itself!
I must be missing something here...

Is it possible to check the app at a system *without* any Python 3 installations?

**Comment by retrography** [comment]
Oh, now I see. You are right, there are only aliases. I just copied the python binary manually in the bundle and re-uploaded the zip file. Would you mind downloading and trying it again?

**Comment by noembryo** [comment]
Nope, doesn't run.
It seems that its still looking for your 3.9 installation..

This is what I get when I run the `Python3` executable:
![Mac2](https://user-images.githubusercontent.com/24675403/101096507-52928f00-35c8-11eb-8229-ba8f2c802de3.jpg)

**Comment by retrography** [comment]
It is still searching for Python DLLs. The VENV solution is what the developer of Platypus suggested for creating self-contained executables out of Python scripts. Apparently there are issues with that. Let me find another solution.

**Comment by noembryo** [comment]
Bummer...
Thank you for your time though :o)

**Comment by retrography** [comment]
I couldn’t find a proper way to do it, given that Platypus doesn’t package well, py2app is outdated and pyinstaller runs into errors on Big Sur. I just discovered PyOxidizer, though, and I will give it a shot when I find some time.

**Comment by noembryo** [comment]
@retrography If you succeed in the creation of a MacOS binary, notify me to upload it in the newer release..
Thank you for your time.

**Comment by retrography** [comment]
I have managed to build it using Nuitka, PySide and Qt4 (which is supported by Nuitka), but that Qt version is visually broken on MacOS with high dpi. On the other hands, it seems PySide2 has issues, not only with Nuitka, but also with the other Python compiler suites. So, I am stuck with a dilemma where PySide2 is not supported by exe makers, and PySide + Qt4 do not work properly on modern MacOS (or I fail to see how).

I have also tried patching KoHighlights into using PySide2/Python3/Qt5 uniquely by removing backward compatibility. It looks great on MacOS! I then minimally patched Nuitka and tricked it into doing with PySide2 what it normally does with PySide to package it. It seems to do well, except that it keeps searching for a few dependencies under the wrong directories (in system folders, etc). If you want I can upload these somewhere for you to see. But my conclusion is that unless PySide2 issues with compilers are resolved, it is very difficult to produce self-contained execs of KoHighlights for MacOS. Meanwhile, it may be possible to make an executable with a single dependency (e.g. Qt5). Worth trying?

**Comment by noembryo** [comment]
The last couple of releases include an archive with PySide2/Python 3 source files.
I have test them on Windows using Python 3.7.2 and they work OK.
So you just have to find a way to fix your PyInstaller problem (which is what I use both in windows and Linux)

**Comment by elain** [comment]
> download

Error (400)
Something went wrong. Don't worry, your files are still safe and the Dropbox team has been notified. Check out our [Status Page](https://status.dropbox.com/) to see if there is a known incident, our [Help Center](https://www.dropbox.com/help) and [forums](https://forums.dropbox.com/) for help, or head back to [home](https://www.dropbox.com/home).

**Comment by noembryo** [comment]
@elain Is your message connected with the compiling of a mac OS X binary that is discussed in this issue somehow?

**Comment by thelazyoxymoron** [comment]
Sorry for the necrobump. Is there any way to make this work on Mac? I checked out the earlier comments but I'm afraid I have little understanding of the python compiler ecosystem. Would love any pointers on trying to make this work for MacOS.

**Comment by noembryo** [comment]
Although there is no compiled binary for Mac, you can still run the scripts from the [Source code (zip)](https://github.com/noembryo/KoHighlights/archive/refs/tags/v2.0.3.0.zip) (or the [KoHighlights.v2.0.3.0.PySide6.zip](https://github.com/noembryo/KoHighlights/releases/download/v2.0.3.0/KoHighlights.v2.0.3.0.PySide6.zip)).
The difference is in the version of PySide used (PySide2 or Pyside6).

To do that you need a Python 3.xx installed on your system (current OSX must have something newer than version 3.6+ that is the minimum).
You must also install the [library's dependencies](https://github.com/noembryo/KoHighlights#dependencies).
After that you only have to open the terminal, `cd` to the scripts folder and run `python main.py` (or `python3 main.py` ).
If this run ok, I'm sure you can find a way to do it with a simple shortcut..
