### ISSUE TITLE
KoHighlight on Flathub

### ISSUE THREAD

**Issue by ploum** [noembryo/KoHighlights#11]
It would be awesome to have KoHighlights packaged as flatpak on Flathub.org so it is easily installable on every Linux distribution.

**Comment by noembryo** [comment]
Yeap!
My main problem is that I know close to nothing about Linux and its distribution system.
To create the Linux version of the app I use XUbuntu in a virtual machine and that's the extend of my knowledge.

OTOH, if someone could use the source to create the package and maintain it, I would really appreciate it...
