### ISSUE TITLE
Android Device not recognized in "Scan Directory"-dialogue

### ISSUE THREAD

**Issue by Steiner91** [noembryo/KoHighlights#13]
Hi, 

your tool is greatly useful all in all, I have however one little issue that makes exporting notes more cumbersome than it needs to be. I use a Likebook Mars as ereader and this device is unfortunately not recognized when I want to scan its book directory. I attached a screenshot, where you can see this:
![2021-04-04 (2)](https://user-images.githubusercontent.com/39560458/113510890-48c06e80-955d-11eb-9fa0-472615d4ea20.png)
My ereader appears as Likebook-T80D in the file explorer, but not in KoHighlights. Is there any way to fix this?

Best regards and thanks in advance.

**Comment by noembryo** [comment]
AFAIK in android readers when you press the `Scan Directory` button and select the the  reader's drive (that I assumed you did),  KOHighlights searches it for a directory named `Koreader`, which in turn must contains a directory named `History`, that has all the metadata files of the read books.
A way to make it more specific is to select the `History` directory yourself.
Does your system contains these folders?

**Comment by Steiner91** [comment]
Thanks for your quick answer, I guess I was too unspecific. The problem is, that the reader's drive is not listed in the  _Scan Directory_-browser at all, so I can't select it.

**Comment by noembryo** [comment]
Hmm..
That could mean that the partition that the android system presents to windows is not a normal USB Mass Storage device.
I would guess its an [MTP drive](https://www.howtogeek.com/192732/android-usb-connections-explained-mtp-ptp-and-usb-mass-storage/#:~:text=MTP%20stands%20for%20%E2%80%9CMedia%20Transfer,Media%20Player%20and%20similar%20applications.).
The only solution to this, is to copy the `History` folder manually to a normal drive and select it with the `Scan Directorry` button..

**Comment by Steiner91** [comment]
Yes, it is an MTP drive, the reader gives no other option unfortunately. 
Ah, that's a pity, and there is no easy way to implement support for MTP drives?

**Comment by noembryo** [comment]
Unfortunately this layer of functionality (the file selector) is provided by Qt4 itself (PySide) so there is nothing I can do to add support for MTP :disappointed:
