### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Prometheus121** [noembryo/KoHighlights#14]
Hi, thank you very much for your work. It'll be very useful, but I'm having a problem installing it.

I get a "Fatal error detected" -  "Failed to execute script main"

Could you please help me?

Thanks

**Comment by noembryo** [comment]
Can you give me some info for your system (basically your OS and anything else you think is relevant)?

**Comment by Prometheus121** [comment]
Windows 10 Home Edition
Intel Core i5 CPU, 3,2GHz
8gbRAM
x64

**Comment by noembryo** [comment]
Can you check if there is an `"error_log_xxxx-xx-xx.txt"` inside your `"C:\Users\USERNAME\AppData\Roaming\KOHighlights\error_log_2021-05-21.txt"`?
If there is, what does it says?

**Comment by noembryo** [comment]
To see the `AppData` folder you have to enable the "Show hidden files" feature of windows Explorer...

**Comment by Prometheus121** [comment]
Thank you for your help.

I don't have a folder with that name. Tried installing with admin privileges', but still no folder...

**Comment by noembryo** [comment]
Another thing you can try, is to install the program again while you have switched off all your antivirus , anti malware, anti whatever..
It is very common for some of them to block files that they shouldn't. :wink:

**Comment by Prometheus121** [comment]
Tried it.
Same error :(

**Comment by pacatito** [comment]
same here

![image](https://user-images.githubusercontent.com/86926465/124395941-595bbe80-dcdd-11eb-82ed-3a42cfe58990.png)

**Comment by noembryo** [comment]
> same here

Are you sure there is no antivirus enabled (like windows build in antivirus)?

**Comment by pacatito** [comment]
yes, i installed it more than two times, enabled and disabled

by the way, ty for  answer so quicky

**Comment by noembryo** [comment]
> yes, i installed it more than two times, enabled and disabled
>
Then, unfortunately there is nothing I can do.. :disappointed: 

:bulb: BTW, have you tried any earlier releases?
