### ISSUE TITLE
removing some books info removes whole sdr folder

### ISSUE THREAD

**Issue by richo67** [noembryo/KoHighlights#17]
Hi,
today I discover when I select few lua files belonging to the same book (but not all) and press DEL, KoHighlight will remove whole sdr folder with all lua files. Quite shocking. Please take a look at he screen recording (no audio).

https://user-images.githubusercontent.com/9590148/136448142-7e22578d-0b53-471b-bd8d-9fffca9e60ec.mp4

**Comment by richo67** [comment]
OK, I do not see in your code so I can understand, but you already have pointer to that particular file once I select merge, isn't it not much more difficult then open and merge a file than only delte it?

**Comment by noembryo** [comment]
I can always access the file. The problem is that I have to add more checks in the "delete actions" that will complicate and slow down the code (you can delete a lot of files at once).
My main objection is that this is an edge case and there is a comfortable workaround already..
