### ISSUE TITLE
Suggestion for some enhancement

### ISSUE THREAD

**Issue by richo67** [noembryo/KoHighlights#18]
Once I am at it :-) I  have some suggestions, If I may:

- One the right side, in book info, can you put there number of comments?
- Would it me possible to sort comments (highlights) based on page number and make it possible to revers so from 1-xxx and than from xxx-1 ?

Thank you for considering.
-r-

**Comment by noembryo** [comment]
>One the right side, in book info, can you put there number of comments?

Maybe not in the book info, but I might find a place to put it.
>Would it me possible to sort comments (highlights) based on page number and make it possible to revers so from 1-xxx and than from xxx-1 ?

You can already do that.
On the `Books` view: `Show in Highlights` button > `Sort by` > `Date` (no reverse though)
On the `Highlights` view there is a page column that can sort the entries anyway we like (also in reverse :wink: )..

**Comment by noembryo** [comment]
>This is not much of use, as it sorts across all the books. If there would be two level sort, first by book, then by,.. ;-)
First sort by page and then by book.. :stuck_out_tongue:
