### ISSUE TITLE
Does not work with Android devices

### ISSUE THREAD

**Issue by eldritchgreene** [noembryo/KoHighlights#21]
The app will not recognize Android devices connected to PC as accessible folders/drives (MTP/PTP protocol) and therefore cannot access files to sync highlights. The only workaround is to copy files from device to PC. Would be great if this could be fixed.

**Comment by noembryo** [comment]
Unfortunately, PySide (who creates the file selectors in the app) does not support MTP communication, and I can't find any other simple implementation, so..

**Comment by eldritchgreene** [comment]
I figured, thanks so much @noembryo the app is great and there is a workaround to this which is to keep a place (or two if multiple devices) on your pc to drop sidecar folders and sync or add to archive from there.  I will continue to use it in this way :)
