### ISSUE TITLE
Not finding *.sdr directories recursively?

### ISSUE THREAD

**Issue by anaxonda** [noembryo/KoHighlights#23]
Hello,

Thank you for KoHighlights. I have used it for a few years to transfer highlights over. Recently I have noticed it is not finding sdr directories recursively, and to show highlights for a book I have individually go into each books *.sdr folder to add it to KoHighlights. In the past, just opening the Kobo root directory would populate KoReader with all the books with highlights.

Is there something I need to change?

**Comment by noembryo** [comment]
It should find the directories recursively.
If it doesn't, something is wrong.
Is there anything strange written to the error.log at KOHighlights settings folder (user/Appdata/Roaming/KOHighlights/)?
Unfortunately I'm on holidays and any checking must wait until I return.. 😞

**Comment by anaxonda** [comment]
I normally launch KoHighlights directly with a terminal, here's what errors I get (soupsieve package is installed):
```
/tmp/_MEII0uyGi/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/home/loki/.config/fontconfig/fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/home/loki/.config/fontconfig/fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/home/loki/.config/fontconfig/fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/home/loki/.config/fontconfig/fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/home/loki/.config/fontconfig/fonts.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/home/loki/.config/fontconfig/fonts.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig error: Cannot load default config file
```

Enjoy your holiday!

**Comment by noembryo** [comment]
So no error.log file in the user settings folder?
I don't remember the exact path in Linux, but it must start with "/home/user/" and end with "KOHighlights". ;o)
What I'm seeing isn't from the app, except perhaps the first line, and it has nothing to do with the problem we check..

**Comment by noembryo** [comment]
Just got back to my box, tried to scan the root of my GloHD and it worked as it should.

So, we must check your configuration.
I'm guessing that you use the compiled binary and not the python script, correct?
Is the same problem exists if you launch it with double clicking the app it self?
Did you found the app's settings directory?

If I can't reproduce it, there isn't a way to fix it.. :disappointed:

**Comment by anaxonda** [comment]
Yes, I use the compiled binary downloaded from the releases page. I launch in terminal via ./KoHighlights.
KDE Dolphin does not allow me to launch via double click currently.
I have not found the app settings directory, where might I do that?

**Comment by noembryo** [comment]
>KDE Dolphin does not allow me to launch via double click currently.

What kind of file manager does that? Weird..
>I have not found the app settings directory, where might I do that?

It should be at the user part of the file system, something like `~/.config/KOHighlights/`
You're looking for a log file named `error_log_xxxx-xx-xx.txt`, where `xxxx-xx-xx` is a date.

**Comment by anaxonda** [comment]
> What kind of file manager does that? Weird..
Seems to be an old bug. I tried launching via double click in thunar
file manager, and voile KoHighlights
worked as expected. All books and highlights available.
> It should be at the user part of the file system, something like
> `~/.config/KOHighlights/`
Got it. Nothing remarkable in the error I guess. Here is
'error_log_2022-10-12.txt':
```
***@***.*** 23:30:05

***@***.*** 23:30:07

***@***.*** 23:30:11

***@***.*** 23:30:13
```

I guess that solves my problem, I'll just launch via double click now.

Cheers

**Comment by noembryo** [comment]
>I guess that solves my problem, I'll just launch via double click now.

Yeah. If there is no error to check, I'll consider this solved. :+1:
