### ISSUE TITLE
Would it be possible  to additionaly provide a command line interface

### ISSUE THREAD

**Issue by m040601** [noembryo/KoHighlights#3]
Example pyglossary, https://github.com/ilius/pyglossary/
Although it is a GUI python application (using another framework, GTK)
the command-line interface, works in all operating systems without any specific requirements, just type:
python3 pyglossary.pyw --help

**Comment by noembryo** [comment]
I could implement some simple commands, but almost all actions are depending on the GUI.
I could write new ones I guess. :o)
If you have any suggestion I could add them to the next release.

**Comment by noembryo** [comment]
OK. Added some basic cli.
@m040601 please check if it is what you want
(never done any cli before, so please make suggestions if something is wrong)
