### ISSUE TITLE
"failed to execute script main"

### ISSUE THREAD

**Issue by vrmneto** [noembryo/KoHighlights#33]
I'm tempted to use kohighlights on win11 but it doesn't work. This error always appears

I have a version 1.6 that I managed to make work after a friend edited some things, but I always try to update and the same error appears
![124395941-595bbe80-dcdd-11eb-82ed-3a42cfe58990](https://github.com/noembryo/KoHighlights/assets/68965241/28d26015-0135-40f3-8609-a5e1b3517202)

**Comment by vrmneto** [comment]
> Can you please be more specific?
> 
>     * I suppose you're using the setup version?
I am using this version KOHighlights v1.7.5.0

>     * This error is from what version?
 v1.7.5.0
> 
>     * Did you try with the last version v1.7.5.0?
yes
> 
>     * Anything strange during the installation?
nothing
> 
>     * Did you try to install it while (totally) closing your anti-virus system?
no, how do i do it?
> 
>     * What editing did your friend, and at what files?
i don't know, but i can send you the archive if you want, I still have it
> 
> 
> You have to give me something more than the error popup.. 😉
sorry, I am not from the computer science area, so I din not know where to start

**Comment by noembryo** [comment]
> sorry, I am not from the computer science area, so I din not know where to start

Don't worry, I was just kidding.. 😃 

Well, forget everything I told you and try the v1.7.4.0..
v1.7.5.0 has a problem that I will fix with the next update..
Sorry for the inconvenience.. 😞

**Comment by vrmneto** [comment]
> > sorry, I am not from the computer science area, so I din not know where to start
> 
> Don't worry, I was just kidding.. 😃
> 
> Well, forget everything I told you and try the v1.7.4.0.. v1.7.5.0 has a problem that I will fix with the next update.. Sorry for the inconvenience.. 😞

Thankx it has just worked even better =))

**Comment by vrmneto** [comment]
Thankx it has just worked even better =)

**Comment by noembryo** [comment]
Released [v.1.7.6.0](https://github.com/noembryo/KoHighlights/releases/tag/v1.7.6.0).. 🥳 🎆
