### ISSUE TITLE
Archiving Files error

### ISSUE THREAD

**Issue by animacio** [noembryo/KoHighlights#36]
Archiving Error (kobo libra color, koreader)
Crash@2024-07-16 09:43:19
Traceback (most recent call last):
  File "main.py", line 998, in on_archive
KeyError: 'pos0'

Please advise

**Comment by noembryo** [comment]
Unfortunately I'll be away from my computer for a couple of weeks.
I'll look at it as soon as I return.
Sorry for the inconvenience.. 😞

**Comment by animacio** [comment]
Thank you!

**Comment by noembryo** [comment]
Can you please send me the .sdr folder that triggers this error?

**Comment by animacio** [comment]
Yes, Thank you!
[ArchiveError.zip](https://github.com/user-attachments/files/16433915/ArchiveError.zip)

**Comment by noembryo** [comment]
Fixed with [v2.0.3.0](https://github.com/noembryo/KoHighlights/releases/tag/v2.0.3.0)

**Comment by animacio** [comment]
Thank you!! Archiving works.
