### ISSUE TITLE
Sync group function not working with large epub files (tested with v. 2.0.3 and 2.02) 

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#37]
I am no longer able to sync / merge highlights on at least two epubs I am currently reading even when I place both .sdr folders on the hard drive.  The issue is also present when I open the .sdr using "Scan Directory" and try to sync it with the archived version.   The  files are attached. 
[Larchet.zip](https://github.com/user-attachments/files/16571492/Larchet.zip)

**Comment by noembryo** [comment]
Thank you for the heads up.
Will be fixed with 2.0.4..

**Comment by noembryo** [comment]
Fixed with 2.0.4

**Comment by edo-jan** [comment]
It works now. Thank you!
