### ISSUE TITLE
Hightlight page number inconsistency

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#38]
**Context:** 
As we discussed previously, koreader's page numbering is dependent on the device resolution / font sizes, etc (unless it uses publisher provided page numbers). While waiting for a permanent solution by the devs I have implemented a "logical page count" user patch  from **[2-logical-page-count.lua](https://gist.github.com/dmalinovsky/69fd68af7848008b1cc80a76961f2d77)**  
This works well across all devices tested (i.e. under android, kobo and linux) Also, the devs implemented markdown export based on the logical page numbers (see the closed issue at the bottom of the [page](https://github.com/koreader/koreader/issues/9020)). 
**Current issue:**
When I sync my annotations the page numbers in Kohighlights are all over the place while they are being displayed correctly (i.e. with the same logical numbers) across my devices

**Enhancement requested:**
I wonder if it would be possible to implement the logical page number support in Kohighlights and use this option for markdown export.

**Comment by noembryo** [comment]
>Current issue:
When I sync my annotations the page numbers in Kohighlights are all over the place while they are being displayed correctly (i.e. with the same logical numbers) across my devices

I don't think that this is the case anymore.
There are a couple of things changed since our last conversation.

-  Every time a book version is synced with a version that has different number of pages, KOHighlights recalculate the current page, using the total number of the pages for this version and the `pos0` of the CRengine that is part of the highlight's info.
This is not really accurate (~± 1-10 pages depending on the book's format), but it's close enough not to be "all over the place".
- After syncing the highlights, KOHighlight marks the metadata in a way the makes KOReader recalculate the highlight's page numbers from scratch on the next opening of the book, so you end up with accurate numbers.

As for the user patch, I don't understand what that code snippet does.
There is no logic that I can recognize there since I never used a user patch, but I suspect that there is some code hidden somewhere that I can't find.
Please, enlighten me..

**Comment by edo-jan** [comment]
> 
> I don't think that this is the case anymore. There are a couple of things changed since our last conversation.

You are correct. I was looking at the old archived view. The pages are now displayed in order. However the numbers are  different from those displayed by the devices with the user patch turned on. 

> 
> As for the user patch, I don't understand what that code snippet does. There is no logic that I can recognize there since I never used a user patch, but I suspect that there is some code hidden somewhere that I can't find. Please, enlighten me..
I wish I could. Unfortunately, I don't know much about the patch code other than the fact that it works ... lol...   Maybe we can ask the guy who developed it.  My issue is that the pages displayed in Kohighlights view are different from those displayed by the devices. If we only could harmonize them

**Comment by noembryo** [comment]
> However the numbers are different from those displayed by the devices with the user patch turned on.

I can't help with this, since I don't know how the patch work.
> My issue is that the pages displayed in Kohighlights views are different from those displayed by the devices. If we only could harmonize them

.. but this, I can't understand.
You're saying that after the sync and after at least one opening with the device, the highlights page number are still wrong if you see them with KOHighlights?
This can not be the case, since, as I told you, KOReader recalculates the page numbers..

**Comment by edo-jan** [comment]
> > My issue is that the pages displayed in Kohighlights views are different from those displayed by the devices. If we only could harmonize them
> 
> .. but this, I can't understand. You're saying that after the sync and after at least one opening with the device, the highlights page number are still wrong if you see them with KOHighlights? This can not be the case, since, as I told you, KOReader recalculates the page numbers..

Let me make it a bit more clear. What I meant is that Kohighlights displays page numbers which are  _different_  from those displayed by the devices with the user patch installed and the feature "use reference page numbers" is checked.   These "reference" page numbers are exactly the same across all my devices and the book marks also display the "reference" pages for each bookmark.  Now when Ioad the .sdr into kohighlights the it shows a _different_  page numbers for the highlights / annotations.

**Comment by edo-jan** [comment]
here is the screenshot illustrating the above
![pages2024-08-14_003139](https://github.com/user-attachments/assets/a6532bfd-61f2-4511-96e9-953eb6b98017)

**Comment by noembryo** [comment]
Yes, I see.
But unfortunately, since I don't know how the get these logical page numbers, I'm afraid I can't help you with this.. 😔

**Comment by edo-jan** [comment]
Let me try to find out more information about this.  On a related note, I remember there was some talk about the Koreader's devs considering something similar to logical page numbers : Do you know if there's been any movement on this?

**Comment by edo-jan** [comment]
hi noembrio, I contacted the author of the user patch and he responded (please [read it here](https://gist.github.com/dmalinovsky/69fd68af7848008b1cc80a76961f2d77?permalink_comment_id=5156587#gistcomment-5156587)). I hope you will find the information he provides to be helpful.

**Comment by noembryo** [comment]
Hmm..
Unfortunately, that means that it uses a KOReader's function, that uses the CRengine to get the text of the book and calculate the page based on that.
The only way to have these numbers is for KOReader to add them to the annotation's info (in the book's metadata).

**Comment by edo-jan** [comment]
A big thanks for trying!  I have a silly question though: am I beating a dead horse? Is it possible that this was already solved by some other method and I am (being not too technical) simply failed to realize this?  Is there a way to have **_consistent_** page numbers in different devices / screen sizes / resolutions that are exportable to  kohighlights by using some other method?

**Comment by noembryo** [comment]
> Is there a way to have consistent page numbers in different devices / screen sizes / resolutions that are exportable to kohighlights by using some other method?

Searching for this new logical (synthetic) pages I read many conversations that are asking the same question.
I think the answer is "none that I know of".

The only fast and simple way that I know, is the Adobe Digital Editions (a page for each 1024 bytes of the book's file size).
This is used in many readers for "fixed" page numbers, but it is highly inaccurate (more images in the book, more pages are calculated).
I think that the ADE method is not supported in KOReader, and I believe rightly so..
KOReader's method is much better (more realistic) but I think only KOReader use it.

I asked a dev if it's possible to add the calculated pages in the metadata, and I'm waiting for an answer, so maybe there is hope for the future 🥳  (or maybe not 🤷‍♂️).

**Comment by edo-jan** [comment]
🙏

**Comment by noembryo** [comment]
If you're not following the thread with the request, check this [answer](https://github.com/koreader/koreader/pull/12214#issuecomment-2294634427)..

**Comment by noembryo** [comment]
Can you check your metadata files (or even better upload them here), that have been processed with the user patch that you're using, if they contain a `pageref` key for every annotation, that contains the correct page number, the one  that you see inside KOReader?

**Comment by edo-jan** [comment]
> Can you check your metadata files (or even better upload them here), that have been processed with the user patch that you're using, if they contain a `pageref` key for every annotation, that contains the correct page number, the one that you see inside KOReader?

The _pageref_ keys are there and they contain the calculated reference page numbers! 🙏😍😍🙏I am attaching the metadata file (the same book used in the screenshots above). You can see that the pageref numbers are the same as those shown on the bookmark view of the phone's screenshot 
[metadata.epub.lua.zip](https://github.com/user-attachments/files/16645219/metadata.epub.lua.zip)

**Comment by noembryo** [comment]
Here is a [beta version](https://mega.nz/file/jI9TBKAJ#0nxSUH-p1n9KgiPVjajRQR10qJjKWhEXHzHlXvN9INU) with reference page number support.
Check if there is anything problematic about it..

**Comment by edo-jan** [comment]
Thanks for implementing! I can see the reference numbers are correctly showing once the "Reference Numbers" is selected.   The only issue I can see so far is the incorrect total page numbers displayed in the metadata under the Book view (the "Pages" field  located next to the "Language" field).  For example, the book for which I sent you the metadata file above shows total number of pages in all my readers as 2494. Koghilight's "Pages" field for the same book shows 9600.

**Comment by noembryo** [comment]
Yes, I saw that too, but unfortunately there is no info for that in the metadata file..

**Comment by edo-jan** [comment]
As a [not too perfect] workaround consider hiding the "Page" field if the "Reference Numbers" option is checked. Just an idea

**Comment by edo-jan** [comment]
Here is a couple of other small issues. 
1. Note the screen artefacts during the start up
2. The book list in the archive is not loaded during the start up. One needs to change the view from "Archived" to "Loaded" and back to "Archived" in order to see the books 

https://github.com/user-attachments/assets/70f02543-daef-42a1-bb89-fb959e61653d

**Comment by noembryo** [comment]
> As a [not too perfect] workaround consider hiding the "Page" field if the "Reference Numbers" option is checked. Just an idea

I can do that for now, but I don't like it that much.
> * Note the screen artefacts during the start up

Fixed.
> * The book list in the archive is not loaded during the start up. One needs to change the view from "Archived" to "Loaded" and back to "Archived" in order to see the books

Fixed.

New beta [here](https://mega.nz/file/TVMVmDrK#wXq2ez4HaN1QIeXHlhI2LLRP4H3sesgScEgpRmYKYas)..

**Comment by edo-jan** [comment]
Thank you we are almost there!
2.0.4.2 issues:
Issue 1. The startup always defaults to the highlight view. The desired behavior is to remember the last view. E.g. if the program was closed in Book/Archived view, then it should open from there. Likewise, if was closed in Sync view should open in sync view.

Issue 2. The hilight view columns can be re-arranged but are not memorized. E.g. I like to have the "Page" to be the first column, followed by Chapter, Highlight, and Comment.  After the program restarts it is back to the default. 

Issue 3. The filter state under the Highlight view is not remembered. The desired behaviour would be to remember the last filter(s) applied and show the "Filter" button depressed that would indicate that there are some filters applied.

**Comment by noembryo** [comment]
> Thank you we are almost there! 

🤣🤣🤣🤣🤣
>2.0.4.2 issues: Issue 1. The startup always defaults to the highlight view. The desired behavior is to remember the last view. E.g. if the program was closed in Book/Archived view, then it should open from there. Likewise, if was closed in Sync view should open in sync view.

And this is how it works, …except for the Sync View.
The reason I disabled it there, is because, depending on the number of the groups you have, it can take some time until they are fully loaded.
I will enable it for this beta to test it a little and see if I can leave it enabled..
> Issue 2. The hilight view columns can be re-arranged but are not memorized. E.g. I like to have the "Page" to be the first column, followed by Chapter, Highlight, and Comment. After the program restarts it is back to the default.

Yes, I have thought about it when I first made the Highlights view too, and it was on the todo list for the future, but..
OK, done. 😉 
> Issue 3. The filter state under the Highlight view is not remembered. The desired behaviour would be to remember the last filter(s) applied and show the "Filter" button depressed that would indicate that there are some filters applied.

This is not how the filter works.
The filter dialog is the same for all views and it gets reset when changing a view because it works in a different way depending on the view.
When the dialog is open, the Filter button is pressed.
When the filter dialog is closed, no filtering is applied and the Filter button is depressed.
That way, there is always a visible indicator for when filtering is happening.

The newer beta is [here](https://mega.nz/file/jZdHyAII#z6_fdXU8-zTCCm7-kn5n3UgGpqS4mdTveWKSfMOvGOo)..

**Comment by edo-jan** [comment]
> > Thank you we are almost there!
> 
> 🤣🤣🤣🤣🤣
> 
🤩🤩🤩

I will test the newer beta later tonight. In the meantime, I have observed that the path specified in the Archive view sometimes changes for no reason.  Here is how you can replicate it as far as I can tell: 
Preconditions: a sync group exists for a book on two diferrent devices (e.g. the first .sdr is on C:/ and the second is on F:/ - i.e. a reader such as Kobo )  
1) Go to the Books/Loaded view and load the .sdr from C:/ drive.
2) Archive the book (under the Archived view this should correctly show the path pointing to C:)
3) Go to the Sync view, make sure "Sync with archived" is checked and run the sync for the group
4) Eject the reader, restart Kohighlights 
5) Now go to the Books/Archived. The path for the archived book changes to F:/ drive and a warning triangle sign appears with a note "epub file is missing".   

The difficulty is that this does not happen 100% of the time but eventually many of my sync groups end up showing the missing file warning for at least one or two books.  I noticed that if there is no backup file pre-existed before the first "sync with archive"  the system creates Archive pointing to the connected device (in my case the F:/ drive). When the device is no longer connected it then shows red. I am not too clear why the path to the "Archived" shows the device directory in the first place. It is not where the Archived file is stored - am I wrong?

**Comment by noembryo** [comment]
From the top of my head, when archiving after a sync, the version of the book that is copied over to the db is the most recent one.
So, if the most recently modified (for adding/editing annotation in the reader) version is the one at F:\, then this is the one that is archived..
I'll check the code later, to be sure..

**Comment by edo-jan** [comment]
> EDIT: Yes, it's the newest one that is archived.

Is there a reason to display the error about the missing file then? Or even the entire path given that this is not where the real archive is stored?

**Comment by noembryo** [comment]
There is not one "real archive" when you're syncing multiple files.
All are real.
There is no way that the app can predict that you're going to disconnect one drive in the future, so it will store something else in the archive.
It archives the newest ,because this one has probably the most updated info in general.
The path is displayed as info for the user that it can be ignored if the user does not want to open the book itself.

**Comment by edo-jan** [comment]
Ok, now I understand how it works. Do you think in the future (one day maybe) it would make sense to make the system create a separate reference file (i.e. a real archive or better call it a system copy) which would store the latest sync version on a book level?  Among other benefits this would enable actually deleting highlights / annotations from all books at once, when the user edits entries directly in the system copy.  Currently, if I delete an entry from one book the syncing brings it right back... lol.

**Comment by noembryo** [comment]
> Do you think in the future (one day maybe) it would make sense to make the system create a separate reference file (i.e. a real archive or better call it a system copy) which would store the latest sync version on a book level?

By "book level" you mean storing the book as well?
For what purpose?
>Among other benefits this would enable actually deleting highlights / annotations from all books at once, when the user edits entries directly in the system copy. Currently, if I delete an entry from one book the syncing brings it right back... lol.

I don't think that this will ever be possible, because when syncing two versions of a book, and one has an annotation that the other doesn't, there is no way for the app to know that the first one had this annotation at a previous time (say yesterday) and you since then deleted it, so it should delete the annotation in the version that currently has it.

**Comment by edo-jan** [comment]
> > Do you think in the future (one day maybe) it would make sense to make the system create a separate reference file (i.e. a real archive or better call it a system copy) which would store the latest sync version on a book level?
> 
> By "book level" you mean storing the book as well? For what purpose?
> 
Sorry I did not make it clear. I meant for every sync group. That is the system would create and store "system copies" of the metadata files containing the latest synched highlights / annotations for each book (that is one metadata file for each sync group).  

> > Among other benefits this would enable actually deleting highlights / annotations from all books at once, when the user edits entries directly in the system copy. Currently, if I delete an entry from one book the syncing brings it right back... lol.
> 
> I don't think that this will ever be possible, because when syncing two versions of a book, and one has an annotation that the other doesn't, there is no way for the app to know that the first one had this annotation at a previous time (say yesterday) and you since then deleted it, so it should delete the annotation in the version that currently has it.

This is correct. But the idea is not to alter the current behavior. It is to add an editable system copy (e.g. to be editable in the Highlights view) which can be included into the sync group with an option to overwrite the metadata files on selected devices within the sync group.  If one checks the "replace with system copy" option for specific device(s) in a group, that device's metadata file will be overwritten by the system copy. If one keeps the option unchecked (the default) the system copy will just store the latest version of the synced highlights for the sync group.

**Comment by edo-jan** [comment]
Moreover, this would enable a true cross device annotation editor one could use to edit / enhance annotations for the given book before exporting to an external app (such as Obsidian) for further processing. The resulting system copy could be used to overwrite the unedited versions on the devices...

**Comment by noembryo** [comment]
> Sorry I did not make it clear. I meant for every sync group. That is the system would create and store "system copies" of the metadata files containing the latest synched highlights / annotations for each book (that is one metadata file for each sync group).

This is exactly what archiving does.
It stores a copy of the .sdr metadata to the database.
> But the idea is not to alter the current behavior. It is to add an editable system copy (e.g. to be editable in the Highlights view) which can be included into the sync group with an option to overwrite the metadata files on selected devices within the sync group. If one checks the "replace with system copy" option for specific device(s) in a group, that device's metadata file will be overwritten by the system copy. If one keeps the option unchecked (the default) the system copy will just store the latest version of the synced highlights for the sync group.

There is a dangerous idea there.. 💣, but an idea never the less.
What you're proposing is an option to copy the archived metadata to all the items of a sync group.
This is not that difficult to implement..

**Comment by noembryo** [comment]
I will have to think about the implementation though, and it will probably have to wait for the next update, since after this update, I will be away from my PC for a while..

**Comment by edo-jan** [comment]
> I will have to think about the implementation though, and it will probably have to wait for the next update, since after this update, I will be away from my PC for a while..

Thank you! This would really boost usability.  In the meantime I am thinking of putting together a basic user guide describing some of the ways one can use Kohighlights. In my view many people out there have no idea that this tool exists / how it can address their needs.

**Comment by noembryo** [comment]
OK. I caved in and add it to the group's right click menu..
Tomorrow I'll release it (if I didn't broke anything else with all that changes.. :).

**Comment by noembryo** [comment]
> In the meantime I am thinking of putting together a basic user guide describing some of the ways one can use Kohighlights. In my view many people out there have no idea that this tool exists / how it can address their needs.

That's very nice..

**Comment by noembryo** [comment]
Forgot to post the [link to the new beta](https://mega.nz/file/CEM1UR6b#1DKSwtgS_Z3NULwbbKlbhU_qvIjB_E9EeaD5_ccKt4c)..

**Comment by edo-jan** [comment]
I have created a test group and trying to add a book which is not being recognized. It is displayed in red color, but it is the same book but for whatever reason (based on a hash value?) it is being rejected.  This is not the first time I am struggling with "false positives" likely because (this is my wild guess) it might have been opened in a Calibre viewer which if I am not mistaken stores in the epub some kind of metadata.  Is there a simple way to fix this type of issues?

**Comment by edo-jan** [comment]
Just discovered that this happens when a book's settings in Koreader is changed via "reset document's settings to default"
After this setting is applied to a book in Koreader then its metadata file loaded in Kohighlights is no longer being recognized as a legit member of its sync group.

**Comment by edo-jan** [comment]
In both cases the the unrecognized book is the one on the C:/ drive.  In the group below it causes the other two to go red because it appears first in its sync group.  
![2024-08-22_232140](https://github.com/user-attachments/assets/b96e40c3-e44e-4648-a4b7-119b76f6d97b)

**Comment by edo-jan** [comment]
![2024-08-22_232608](https://github.com/user-attachments/assets/64b6ff6e-d62a-4219-a385-e3918c07df0a)

**Comment by edo-jan** [comment]
> > Just discovered that this happens when a book's settings in Koreader is changed via "reset document's settings to default"
> > After this setting is applied to a book in Koreader then its metadata file loaded in Kohighlights is no longer being recognized as a legit member of its sync group.
> 
> This action just deletes the `.sdr` folder and then re-creates it, using the book. That means that it will also recalculate the `partial_md5_checksum` that defines the book's ID. If the book was previously been modified, the new md5 will be different from the one before, hence the problem with pairing with the other versions of the metadata. You can check it yourself. If it's the same, then you must send me the problematic metadata, along with at least one of the normal ones..

Are you sure if the .sdr is deleted and recreated from the book?  When the "reset document's settings to default" is used on a book all highlights and annotations are preserved. It simply applies a bunch of settings such as font size, margins, settings pertaining to status bars, etc.  The name of this feature is somewhat misleading but it is used in conjunction with "Save document settings as default" - see the screenshot above. For example, when I tweak the settings on a book to my liking, I use the latter feature to create a multi-setting default that I can use on other books if I want them to look exactly the same as my tweaked one.  As I said, all pre-existing highlights are preserved intact.   

I just restored the impacted metadata file from backup (attached as "C-original").  
When I load the group with "C-original" the sync group is recognized as legit.  "C-altered" contains .sdr that resulted when the book was opened in Koreader and a couple of formatting settings were changed (specifically I just changed the screen orientation). This imediately caused the .sdr to be rejected.  However, the underlying epub was not altered
 in any way (also attach it just in case). The two other files are from two other devices (one mapped to T drive and the other to E-drive - they are attached in respective folders) 
[sdrs.zip](https://github.com/user-attachments/files/16729051/sdrs.zip)

**Comment by noembryo** [comment]
> I just restored the impacted metadata file from backup (attached as "C-original").
When I load the group with "C-original" the sync group is recognized as legit. "C-altered" contains .sdr that resulted when the book was opened in Koreader and a couple of formatting settings were changed (specifically I just changed the screen orientation).

This is not the case.
"C-original" is identical to "C-altered"

**Comment by edo-jan** [comment]
Somehow I messed it up. Here it is. This one is larger.  
[C-altered2.zip](https://github.com/user-attachments/files/16734321/C-altered2.zip)

**Comment by edo-jan** [comment]
To test this further, I deleted the book's .sdr on C:/ and reopened the book to recreate it to see if the new .sdr will be accepted by the other group members (E & T).  It is also rejected! Please see if the following group works on your side: C-new + E + T
  
[C-new.zip](https://github.com/user-attachments/files/16734360/C-new.zip)

**Comment by noembryo** [comment]
OK, this one has the problem you're describing.
An the reason for it is simple.

As you know, there was a big update for KOReader (and KOHighlights), that changed the way they stored the highlights in the metadata file.
They created the "new" format of metadata.
Metadata that where created before this update were the "old" format metadata.
Now, the problem..
When you open an old format with the updated version of KOReader and you reset the metadata, it changes the metadata format from old to new.
This makes the metadata incompatible with the other, old type metadata.
KOHighlights can't sync/merge different types together.
It supports both the old and the new, but not mixed up.

Another question that I would like to know, is what happens if you have this old format, open it with a current version KOReader and then create a new highlight.
Will it convert all the highlights to the new format (and make it incompatible with the others) or write it in the old format?
If you do something like this, please send me the resulting file.. 🙏

**Comment by edo-jan** [comment]
I have opened the book on all three devices and applied the "reset document's settings to default" to force the conversion to the new format and added some new comments as requested. Here is the good outcome: the books are now are all being recognized as a group.  However, the bad one is that the sync stopped working.  When I try to sync nothing happens (that is the no-confirm bug is back). Here are all three files 
[TEMP.zip](https://github.com/user-attachments/files/16734544/TEMP.zip)

**Comment by noembryo** [comment]
Well, they sync OK here..

**Comment by edo-jan** [comment]
The book synced after I removed from the archive the catched version. But another book is not being recognized.... no luck with this one.  However here is a larger fish to fry. It appears that pageref tag is missing from most books. I think that it is in fact present only where the publisher included it into the epub.  The logical numbers user patch works correctly, and its output can be seen in the Reference page number list, as well as correctly displayed in place of page numbers. However it is not making its way into pageref for most books I initiate with the newer version of Koreader don't show the pageref key in the metadata file...

**Comment by edo-jan** [comment]
in other words when we could see the pageref keys we assumed that koreaders devs have implemented the feature, while in fact it was a book with built-in publisher numbers...

**Comment by edo-jan** [comment]
Just tested the new "Copy Archived to Group" feature. I have first added one annotation to the Archive and deleted a highlight. Then reverse synced it back to the group. The result was that Koreader refused to open the book **on all devices** with an error "No reader engine for the book of this type is found".  Interestingly enough, after this acting on whim I synced the group again but this time normally. Lo and behold, it fixed the issue **on all devices** and correctly showed the added annotation as well as the deleted highlight... The important thing that it worked!

**Comment by noembryo** [comment]
> in other words when we could see the pageref keys we assumed that koreaders devs have implemented the feature, while in fact it was a book with built-in publisher numbers...

So, [this](https://github.com/koreader/koreader/pull/12214#issuecomment-2294822532) is not the case then..
If you're sure about it, you can mention it there to learn about the future plans.

> The result was that Koreader refused to open the book **on all devices** with an error "No reader engine for the book of this type is found".

This is serious! 😦 
Can we find any metadata that triggers this error?
It's essential for understanding what's going wrong..

**Comment by noembryo** [comment]
Made some tests here using KOReader v2024.07 and your "C-original" metadata. This is what I see.
* When KOReader opens the book, if it's an old type metadata, it will copy all the highlights/bookmarks to the new "annotations" key and leave the original unchanged.
* Any new highlights/bookmarks will be stored in the annotations key
* Pressing the "Reset" button, on the long press dialog of the History items, will do nothing to the annotations if the "document settings, progress, bookmarks, highlights, notes" checkbox is left unchecked.
If it's checked, it will clear them all.

So no need to Reset the book "to force the conversion to the new format".
Some of the metadata might be corrupted after all these test, so maybe it is better to start fresh.

Made [a new beta](https://mega.nz/file/mV9GhCYQ#PRlI8-6F8a5tonS2T7hi4OGWSd6YD03XdNrmTqS0iWg) that checks for the type of "pageno" key (better safe..). 
Use this to be certain.
Can't find anything really wrong here.. 🤷‍♂️

**Comment by noembryo** [comment]
This is [the new beta](https://mega.nz/file/vYVwUKLY#pyn6kOKGDpr4kzIlespn_k4ZeoAx-sBPTUjhwWqEApw). The previous one had some problem.

**Comment by edo-jan** [comment]
> * Pressing the "Reset" button, on the long press dialog of the History items, will do nothing to the annotations if the "document settings, progress, bookmarks, highlights, notes" checkbox is left unchecked.
>   If it's checked, it will clear them all.

This is good to know. Thanks

**Comment by edo-jan** [comment]
the latest beta properly worked once (for the reverse sync) after the install and then stopped syncing the books altogether. Overall I have been having lots and lots of stability issues. The program frequently freezes and its process must then be killed manually from the windows task manager. Deleting the archived versions did not help
I am including the error logs + the db files 
[KOHighlights.zip](https://github.com/user-attachments/files/16737614/KOHighlights.zip)

**Comment by noembryo** [comment]
Hmm..
The error that you get in your last log, is one that I had once but never repeat it again, even though I made the same things with the same files etc.
Since you probably found a way to hit it repeatedly, I'll protect this part of the code, although I can't find the source of the problem.
It has to do with a brief period of time, that the `"pageno"` key of the metadata was a string, not a number.
Now it's a number, so it won't happen again with the newer metadata.

The other day's errors was probably due to a corrupted metadata file and a permission denied error.

Hopefully [the new beta](https://mega.nz/file/mFN01byC#mUwCja3nT_QtwoZPUiEC7U_BvyMQjT6IgjA8U67mkJI) will solve your last problems..

**Comment by edo-jan** [comment]
The new beta is working so far. Thanks for the fix.  I have been able to sync the files without errors. I will keep testing

> So, [this](https://github.com/koreader/koreader/pull/12214#issuecomment-2294822532) is not the case then.. If you're sure about it, you can mention it there to learn about the future plans.
> 
I will mention

**Comment by edo-jan** [comment]
The nightly build 2024-07-123 uses `pageref` for logical page numbers! 🍾🥂🍾
Unfortunately, nightly builds are not available for Linux to sync with my PC. So I can only test between Kobo reader and Android phone. To sync with Linux I need to wait until 2024-08 is released which, I hope, is around the corner

**Comment by noembryo** [comment]
So, finally I will release this update too.. 😉 
(Tomorrow, no time for it today)
Also, if you're interested in translating KOHighlights, I might create a way to do so (when I'll be back of course).

**Comment by noembryo** [comment]
Added in [v2.1.0.0](https://github.com/noembryo/KoHighlights/releases/tag/v2.1.0.0)

**Comment by edo-jan** [comment]
> So, finally I will release this update too.. 😉 (Tomorrow, no time for it today) Also, if you're interested in translating KOHighlights, I might create a way to do so (when I'll be back of course).

Will be happy to help with translating the program

**Comment by noembryo** [comment]
> Will be happy to help with translating the program

Thank you.
I'll let you know..
🙏
