### ISSUE TITLE
KoHighlights as database?

### ISSUE THREAD

**Issue by konjski-tramvaj** [noembryo/KoHighlights#4]
Is there a possibility to re-invent KoHighlights not just as utility to view/save highlights but as utility that can save highlights unto itself. That way every time we open KoHighlights we can browse our highlights without connecting device.

Much love from 📚 friend

**Comment by noembryo** [comment]
You can always combine all your highlights to an html (or text) to view them later. (o;

Do you mean that you would like to save lets say, an sqlite database file somewhere and then open this file with KoHighlights instead of browsing a folder?

**Comment by konjski-tramvaj** [comment]
I mean that every time that user loads folder with books read in Koreader that the KoHighlights automatically makes a copy of highlights file unto itself, storing that files in itself [like auto import(without user interaction)]. There is similar tool but only for Kindle; [https://kmate.me/](url), it has auto import and defined words (dictionary) lookup.

**Comment by noembryo** [comment]
So basically you would like the main database concept (from what I can understand from the Kindle Mate).

I don't like that much the "automatically" importing of everything, because it will also slow down the loading for people that don't use the db.
Adding all the books to database could be as simple as "Select All" and "Add to Database"

Also because the UI of KoHighlights is different, you have to have a way to show the database or the actual books you are browsing.

Any thoughts?

**Comment by konjski-tramvaj** [comment]
Yes, auto-loading could be a feature(if there is need for that) but I agree that would be a nuisance.
Regarding UI maybe add one vertical part for the database and imported books (tree). As I understood you can use KoHighlights to sync two devices; maybe add a column from which device highlights are from?

**Comment by noembryo** [comment]
There is no info in the metadata of a book for the device that is in, so I can't have this.
KoHighlights can sync two books, not devices, and to do that you have to load both of them at the same time.

I'm thinking more in the terms of adding a third "view" (other than "Books" and "Highlights") that would be similar to the "Books" one but using the db.

**Comment by konjski-tramvaj** [comment]
Thanks for clarification. Third view could be very good.

**Comment by noembryo** [comment]
Archive view is added.
If you have Python (and the [other dependencies](https://github.com/noembryo/KoHighlights#dependencies) of KoHighlights) you can check the current source.
I have to test it a little more and decide some things before the binary releases.

**Comment by konjski-tramvaj** [comment]
> 
> 
> Archive view is added.
> If you have Python (and the [other dependencies](https://github.com/noembryo/KoHighlights#dependencies) of KoHighlights) you can check the current source.
> I have to test it a little more and decide some things before the binary releases.
> 
> Edit: In Linux you must install the `libqt4-sql-sqlite` package too.

👍 will try to test it today, thanks so much 😉

**Comment by noembryo** [comment]
From v1.0.0.0 there is an "Archived" mode.
