### ISSUE TITLE
Issues in 2.1.1.0

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#41]
Issue 1. program crushes periodically under win 11.  Afterwards the program refuses to start (actually this was occurring in older versions as well).  Here is the error log + db files
[KOHighlights.zip](https://github.com/user-attachments/files/16956052/KOHighlights.zip)

**Comment by edo-jan** [comment]
Issue 2. Some books in sync groups are no longer being recognized after koreader is being updated to newer versions on some devices while other devices remain on older version. This is really becoming a big issue trying to "trick" KH by copying metadata and book files from one device to another. Sometimes it works and sometimes it doesn't
Please, please please 🙏😟🙏 implement a manual override so that one can make KH to accept a book into the group when KH thinks it is different, but the user is sure that it is the same text (the differences can be due to multiple reasons such as Calibre settings, etc.)

**Comment by noembryo** [comment]
Since I'm still away from my computer, I can't check the first issue, but I can answer you about your second one.
I can't implement it, because there is no way that I can synchronize old type highlights with new type ones.
To do so, will require to write a third of the program's code more..
Also, this is a temporary thing, since after some time, all your devices will have a version with the new type of highlights..😀

**Comment by noembryo** [comment]
Also, about your second issue..
The reason the app can't start is a missing file on the E:\ drive.
You can see the path in the last log.
Since I don't have the code to check, I don't know what is requesting it, probably the sync groups, but it might be easy to bypass this..

**Comment by edo-jan** [comment]
> I can answer you about your second one. I can't implement it, because there is no way that I can synchronize old type highlights with new type ones. To do so, will require to write a third of the program's code more.. Also, this is a temporary thing, since after some time, all your devices will have a version with the new type of highlights..😀

I thought this was being caused by the differences in Koreader versions / metadata formats. Unfortunately, this doesn't seem to be the case. I now have v 2024-07.168 on all my devices and I am getting the same issue. To avoid mixing the old (exisitng) .sdrs with new ones created in the newer versions I have started from scratch.  That is new .sdrs were created by Koreader on respective devices and they were added into a sync group. The group is not working.  The only difference is on device 1 the books were loaded using Calibre and on device 2 (phone) - using  Calibre Companion. The differences are due to how both programs name the respective files (I did not find a way to harmonize).  I will send you the metadata files later

**Comment by noembryo** [comment]
As we discuss in an earlier issue, Calibre can repack the epub causing it to have a different checksum.
This checksum is used to tell if two books are the same.
So, you have to tell Calibre not to do this..

If this is not the case, and the book data are having some other difference, then, please upload them here so I can check them when I find the time.

**Comment by edo-jan** [comment]
> As we discuss in an earlier issue, Calibre can repack the epub causing it to have a different checksum. This checksum is used to tell if two books are the same. So, you have to tell Calibre not to do this..
> 

Unfortunately, it doesn't seem to be possible to change this in Calibre. One can only change some settings instructing the program not to save any metadata inside of the epubs.  The same pertains to the built-in reader in Calibre. The issue occurs when Calibre sends books to android using Calibre Companion. The respective epubs produce different checksum numbers in koreader's metadata files under the same Koreader version.  I have tested this on several different books. Currently, the only workaround to make the group sync, is to manually replace the checksum number inside the metadata file on one device with the number from another device.  I wonder if it would be possible to implement this checksum number harmonization as one of the options when one right-clicks on the sync group that contains a "red" entry?

**Comment by noembryo** [comment]
In the Calibre/Calibre reader, I think that there is a setting that says to not save the current reading position.
At least, there was one in older Calibre versions that I had to disable because of that..

As for the bypassing of the checksum, I was thinking about a hack (don't want to make it obvious, because of the many unpredictable side effects it might have).
You could trigger it by create an empty file with a specific name inside the metadata directory.
More details after I see the code..

**Comment by noembryo** [comment]
New beta [here](https://mega.nz/file/GRVghKCQ#bfXnEScE8odNLe8O6R379nXm3iHmuw2thm5Uyo9V_iY)..
You can add an `ignore_md5` file inside any .sdr folder, and the MD5 checksum will be ignored when trying to sync.
A new Preferences panel is added and a few small bugs are fixed.

**Comment by edo-jan** [comment]
Thanks! I should test this and report the results

**Comment by edo-jan** [comment]
Adding  an `ignore_md5` file to .sdr folder works. Thanks for implementing! I think this is a good way to manage the issue manually. Hopefully in future versions this could be added in the GUI yet making it to be inconspicuous (e.g. the feature to become available for selecting when right-click on a "red" entry in the group. And not just any "red" - (e.g. when KH cannot find the metadata file) but "red" due to MD5 mismatch.  Just a thought.  P.S. I also like the new Settings menu !

**Comment by noembryo** [comment]
Fixed/added in v2.2.0.0

**Comment by edo-jan** [comment]
> Fixed/added in v2.2.0.0

The right-click "ignore_md5" is working great. Thank you. You are the best!

**Comment by noembryo** [comment]
Can you send me a book's metadata sample that has chapters with sub-chapters (divided by the ▸ symbol) to make some tests if I find some spare time?
Since it is specific to a user patch, I don't think it will be useful to other users, but I'm curious about the structure.. 🤷‍♂️

**Comment by edo-jan** [comment]
> Can you send me a book's metadata sample that has chapters with sub-chapters (divided by the ▸ symbol) to make some tests if I find some spare time? Since it is specific to a user patch, I don't think it will be useful to other users, but I'm curious about the structure.. 🤷‍♂️

Thanks for looking into this. It would be awesome if you could implement this feature! 🙏 I attach the metadata file for your reference. 
Certainly, for now the only way to record the full chapter path (separated by  the ▸ symbol)  is via the user patch.  However, hius07 who wrote this patch liked the idea and said that one day it may be added as an option in Koreader. [Issue 12480](https://github.com/koreader/koreader/issues/12480#issuecomment-2381087854) 
 
[Systematic Theology, Second Edi - Wayne Grudem.sdr.zip](https://github.com/user-attachments/files/17272097/Systematic.Theology.Second.Edi.-.Wayne.Grudem.sdr.zip)

**Comment by noembryo** [comment]
> It would be awesome if you could implement this feature!

I don't think I can do it.
It's really difficult to implement (the way KOHighlights is structured).
Just playing around with different approaches..

**Comment by noembryo** [comment]
Well, I spoke too soon.. 🤷‍♂️ 
[This version](https://mega.nz/file/OFtSSB6I#haZ9hmb4VBLEsWOKCz9QDogorzFcKal17sptvPSIS2w) has this feature implemented, but since it is about a user patch, it's hidden.
To access it, you have to open the "Edit Markdown template" by right-clicking the "Edit" button.
If this user patch ever make it to the main KOReader features, I will un-hide it..

**Comment by edo-jan** [comment]
> Well, I spoke too soon.. 🤷‍♂️ [This version](https://mega.nz/file/OFtSSB6I#haZ9hmb4VBLEsWOKCz9QDogorzFcKal17sptvPSIS2w) has this feature implemented, but since it is about a user patch, it's hidden. To access it, you have to open the "Edit Markdown template" by right-clicking the "Edit" button. If this user patch ever make it to the main KOReader features, I will un-hide it..

Thanks a lot! Did I say it before that you are the best?  🤩🙏😍🍾🥳🎇  The mapping works great and the collapsible headers look fantastic.  There are only a couple of small quirks to iron out.  The first issue is the excessive spacing between the highlights in the export. Here are the screenshots to illustrate. Note, now we can use Obsidian's bubles such as `> [!quote]` to format the highlights (e.g. to distinguish it from the user notes) 
![2024-10-07 15_54_18-Edit Markdown template](https://github.com/user-attachments/assets/ec2dde5e-d5ca-4a0d-bd68-e3b7b01860c0)
![excessive space](https://github.com/user-attachments/assets/39465e65-3f7c-41c3-a165-97fa58781515)

**Comment by edo-jan** [comment]
The second quirk is manifested when one edits the template so that the comments are formatted as italics (that is by wrapping it with `*` asterisks). When there are no user comments for the given highlight, the output shows two asterisks `**` 
![template italics](https://github.com/user-attachments/assets/ddb0d9c4-5d80-48dc-b19b-cabb6b08a46f)
![output asterisks](https://github.com/user-attachments/assets/55f55be5-3b4e-479c-8dd8-2b2087d8a5f7)

**Comment by noembryo** [comment]
> The first issue is the excessive spacing between the highlights in the export.

Keep in mind that if you split the chapters, you have to omit the chapter part ( {4} ) from the template.
This is one less line there..
Other than that, it depends on the editor I guess.

> When there are no user comments for the given highlight, the output shows two asterisks `**`

This is true for every field that remains blank but the template contains some formatting for it.
This lack of control made me not use templates and create the output programmatically at the first place.
If you want to omit a field, you have to omit its formatting too.

**Comment by edo-jan** [comment]
> This is true for every field that remains blank but the template contains some formatting for it. This lack of control made me not use templates and create the output programmatically at the first place. If you want to omit a field, you have to omit its formatting too.

I suppose most users can live with this
