### ISSUE TITLE
New database is not being created

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#47]
I am trying to create a new (empty) database by using Archived/Create new database/
The program opens a dialog box allowing me to name a new database file. However when I click on "Save" and exit the dialog, no database is created. The only database that remains in C:\Users\name\AppData\Roaming\KOHighlights is the default data.db

**Comment by noembryo** [comment]
And yet another tiny inconspicuous change that ends up to a new bug.. 🤦‍♂️ 
Fixed it in [this beta](https://mega.nz/file/TBsxQZxA#_xq45rVNG7_BHTXko3McpCbdmcx8zn6LhD94Wl_ZSO4).
Thanks for the heads up.

A new think to note if you are using different databases, is that you can drag and drop them to the Book Selector panel while in the Archived mode.

Also a new User Guide tab was added to the about window..

**Comment by edo-jan** [comment]
It works now - Thank you!

> A new think to note if you are using different databases, is that you can drag and drop them to the Book Selector panel while in the Archived mode.

I am not sure what do you mean. Say, I have two databases db1 (with 10 books) and db2 (with 5 books).  And db1 one is currently loaded. What do I drag and drop to the book selector panel? I tried drag/dropping db2 file but it is not allowing me. 



> Also a new User Guide tab was added to the about window..

Works great. When are you planning to put a link on github?

**Comment by noembryo** [comment]
> > A new think to note if you are using different databases, is that you can drag and drop them to the Book Selector panel while in the Archived mode.
> 
> I am not sure what do you mean. Say, I have two databases db1 (with 10 books) and db2 (with 5 books). And db1 one is currently loaded. What do I drag and drop to the book selector panel? I tried drag/dropping db2 file but it is not allowing me.

You have to be in the Books View _**and**_ have the "Archived" button pressed.
Then, if you drag a `.db` file over to the left panel (the one with the book entries), it will be loaded as the current database.
> > Also a new User Guide tab was added to the about window..
> 
> Works great. When are you planning to put a link on github?

When I release the next version of the app.

**Comment by edo-jan** [comment]
> 
> You have to be in the Books View _**and**_ have the "Archived" button pressed. Then, if you drag a `.db` file over to the left panel (the one with the book entries), it will be loaded as the current database.
> 
Hmm.. not working
![2024-11-01_215152](https://github.com/user-attachments/assets/011e9810-a31d-40bd-b978-64e6db669a07)

**Comment by noembryo** [comment]
> You have to be in the Books View _**and**_ have the "Archived" button pressed.
> Then, if you drag a `.db` file over to the left panel (the one with the book entries), it will be loaded as the current database.

Actually, you don't have to be in the Archive mode.
The db is loaded even if you drop it on the "Loaded" mode.
You just don't see the change.
I have to put a popup dialog there..

**Comment by noembryo** [comment]
> Hmm.. not working

Can you drop an .sdr folder to load it to the app?

**Comment by edo-jan** [comment]
> > Hmm.. not working
> 
> Can you drop an .sdr folder to load it to the app?

Nope, not allowing

**Comment by noembryo** [comment]
> Nope, not allowing

That most likely means, that one of the two apps (Explorer, KOHighlights) is running with administrator rights and the other is not.

**Comment by noembryo** [comment]
Hmm..
You're right.
The compiled app does not accept drag and drop.
I have to investigate further..

**Comment by noembryo** [comment]
OK , figured it out.
Check [this beta](https://mega.nz/file/qY8GmDJT#94Wq5YnSU9pFjwT1GMnm5JebVZbaP6zGoRvN3lRzs0c)..

**Comment by edo-jan** [comment]
It works now! Thank you. Is there a way to figure out what database file is currently loaded?

**Comment by noembryo** [comment]
> Is there a way to figure out what database file is currently loaded?

No, but I might think of something..

**Comment by noembryo** [comment]
Check out the System tab in the About dialog..
The database issue is fixed in v2.3.0.0
