### ISSUE TITLE
How do I set this up?

### ISSUE THREAD

**Issue by candideu** [noembryo/KoHighlights#9]
Hello,

I want to set this up to sync and export my KOReader highlights to my computer, but I don't know how to set this up. I downloaded the KoHighlights-1.3.0.0 zip file with all the Python files. Not sure what I'm supposed to click on or do now.

**Comment by noembryo** [comment]
If you are in Windows, get the `KoHighlights.v1.3.0.0.setup.exe` and just install the program.
If you're in Linux, use the Linux binary..

**Comment by candideu** [comment]
I've used the KoHighlights.v1.3.0.0.setup.exe, and kept getting this message:

![image](https://user-images.githubusercontent.com/55474996/86966229-cd00d500-c136-11ea-8c9e-d1272ae8446a.png)
 
Even when I clicked "yes" and installed Visual C++ 2008, I would click on it again and get the exact same message.

**Comment by noembryo** [comment]
You have to download and install the 32bit version (x86)

**Comment by candideu** [comment]
Where is the 32-bit version? The [download page](https://github.com/noembryo/KoHighlights/releases/) only shows one .exe file, and that's the one I downloaded that gave the Visual C++ error:

![image](https://user-images.githubusercontent.com/55474996/87057663-24ee1900-c1d5-11ea-890d-fdead4b1cb71.png)

**Comment by noembryo** [comment]
The 32bit version of Visual C++ 2008

**Comment by candideu** [comment]
Ahh, I see. It works now! Thank you so much for your help @noembryo ! I've been exploring this app for a few minutes and it's exactly what I needed.

For future reference, in case someone else has the same issue with the .exe, [this is the link to the Visual C++ download that solved the issue for me](https://www.microsoft.com/en-ca/download/details.aspx?id=29).

**Comment by noembryo** [comment]
I'm glad it finally worked out for you.. :+1:
